"""Compare new CVBuilder pipeline output against old R/LaTeX pipeline reference.

The old pipeline (Perl + Pandoc + LaTeX → tth) produced a reference HTML file
stored at fixtures/einstein_unc_reference.html.  This test imports the same
Einstein YAML into the new pipeline, renders a UNC-style preview, and verifies
that every substantive content element present in the old output also appears
in the new output.

The reference HTML was generated by:
    cd CVBuilder
    perl ./perl/YAMLtoRefList.pl cvbuilder/backend/tests/fixtures/einstein_refs.yml "reverse"
    cd temp
    pandoc ../cvbuilder/backend/tests/fixtures/einstein_cv.yml \
           --template ../templates/UNCResumeTemplate.tex -o temp_einstein.tex
    pdflatex -interaction=nonstopmode temp_einstein.tex
    tth temp_einstein.tex
"""
import re
from pathlib import Path

from app.services.yaml_import import import_cv_yaml, import_refs_yaml

FIXTURES = Path(__file__).parent / "fixtures"

# ── Helpers ──────────────────────────────────────────────────────────────

def _strip_html(html: str) -> str:
    """Collapse an HTML string to plain text for content comparison."""
    text = re.sub(r"<[^>]+>", " ", html)
    text = re.sub(r"&[a-z]+;", " ", text)
    text = re.sub(r"&#\d+;", " ", text)
    return " ".join(text.split())


def _strip_latex(tex: str) -> str:
    """Collapse a LaTeX string to plain text for content comparison."""
    text = re.sub(r"\\[a-zA-Z]+\{([^}]*)\}", r"\1", tex)   # \cmd{arg} → arg
    text = re.sub(r"\\[a-zA-Z]+", " ", tex)                 # \cmd  → space
    text = re.sub(r"[{}$\\]", " ", text)
    text = re.sub(r"%.*", "", text)                          # comments
    return " ".join(text.split())


def _extract_dois(text: str) -> set[str]:
    """Pull all DOI strings (10.XXXX/...) from a blob of text."""
    return set(re.findall(r"10\.\d{4,}/[^\s,;\"'<>{})+]+", text))


def _extract_years(text: str) -> set[str]:
    """Pull all 4-digit years from text."""
    return set(re.findall(r"\b(1[89]\d{2}|20\d{2})\b", text))


# ── Fixture setup ────────────────────────────────────────────────────────

UNC_SECTIONS = [
    "education", "experience", "awards", "memberships",
    "dissertation",
    "publications_papers", "patents",
    "publications_editorials",
    "publications_chapters", "publications_preprints",
    "publications_letters", "publications_scimeetings",
    "classes", "trainees_advisees", "trainees_postdocs",
    "grants",
    "panels_advisory", "panels_grantreview", "symposia",
    "chairedsessions",
    "consulting", "press",
    "otherpractice",
    "editorial", "peerrev", "software",
    "policypres", "policycons", "otherservice",
    "seminars", "committees",
    "departmentalOrals", "finaldefense", "schoolwideOrals",
]


def _setup_new_pipeline(client, db_session):
    """Import Einstein YAML into new pipeline and create a UNC template."""
    from app.services.pdf import THEME_PRESETS
    import_cv_yaml(str(FIXTURES / "einstein_cv.yml"), db_session)
    import_refs_yaml(str(FIXTURES / "einstein_refs.yml"), db_session)
    resp = client.post("/api/templates", json={
        "name": "Einstein UNC CV",
        "style": THEME_PRESETS["unc"],
        "sort_direction": "desc",
        "sections": [
            {"section_key": k, "enabled": True, "section_order": i}
            for i, k in enumerate(UNC_SECTIONS)
        ],
    })
    assert resp.status_code == 200
    return resp.json()


def _get_old_reference() -> tuple[str, str]:
    """Return (raw_html, combined_tex) of the old pipeline reference.

    The combined_tex includes the Pandoc-generated template .tex PLUS the
    Perl-generated publication .tex files (refs, chapters, letters, scipres),
    since those are included via \\input{} at build time.
    """
    ref_html = (FIXTURES / "einstein_unc_reference.html").read_text(encoding="utf-8")
    ref_tex = (FIXTURES / "einstein_unc_reference.tex").read_text(encoding="utf-8")
    # Append the Perl-generated publication files that were \input{}'d
    for name in ["einstein_unc_refs.tex", "einstein_unc_chapters.tex",
                  "einstein_unc_letters.tex", "einstein_unc_scipres.tex"]:
        path = FIXTURES / name
        if path.exists():
            ref_tex += "\n" + path.read_text(encoding="utf-8")
    return ref_html, ref_tex


# ── Publication content comparison ───────────────────────────────────────

class TestPublicationParity:
    """Verify every publication from the old pipeline appears in the new one."""

    # Titles that appear in both pipelines' publication lists
    EXPECTED_PAPER_TITLES = [
        "Quantum-Mechanical Description of Physical Reality",
        "allgemeinen Relativitatstheorie",
        "Elektrodynamik bewegter Korper",
        "molekularkinetischen Theorie",
        "Erzeugung und Verwandlung des Lichtes",
        "Energieinhalt",
        "Gravitational Equations and the Problem of Motion",
        "Ampere's Molecular Currents",
        "Particle Problem in the General Theory",
        "Quantentheorie des einatomigen idealen Gases",
    ]

    EXPECTED_CHAPTER_TITLES = [
        "Meaning of Relativity",
        "Evolution of Physics",
    ]

    EXPECTED_LETTER_TITLES = [
        "Unified Field Theory",
        "Reply to Criticisms",
    ]

    EXPECTED_MEETING_TITLES = [
        "Present Status of the Problem of Gravitation",
        "Quantum Theory of Radiation",
        "Ether and the Theory of Relativity",
    ]

    def _get_new_html(self, client, db_session):
        tmpl = _setup_new_pipeline(client, db_session)
        resp = client.get(f"/api/templates/{tmpl['id']}/preview")
        assert resp.status_code == 200
        return resp.text

    def test_all_paper_titles_present(self, client, db_session):
        new_html = self._get_new_html(client, db_session)
        for title_fragment in self.EXPECTED_PAPER_TITLES:
            assert title_fragment in new_html, (
                f"Paper title fragment missing from new pipeline: {title_fragment!r}"
            )

    def test_all_chapter_titles_present(self, client, db_session):
        new_html = self._get_new_html(client, db_session)
        for title_fragment in self.EXPECTED_CHAPTER_TITLES:
            assert title_fragment in new_html, (
                f"Chapter title fragment missing: {title_fragment!r}"
            )

    def test_all_letter_titles_present(self, client, db_session):
        new_html = self._get_new_html(client, db_session)
        for title_fragment in self.EXPECTED_LETTER_TITLES:
            assert title_fragment in new_html, (
                f"Letter title fragment missing: {title_fragment!r}"
            )

    def test_all_meeting_titles_present(self, client, db_session):
        new_html = self._get_new_html(client, db_session)
        for title_fragment in self.EXPECTED_MEETING_TITLES:
            assert title_fragment in new_html, (
                f"Meeting title fragment missing: {title_fragment!r}"
            )

    def test_doi_parity(self, client, db_session):
        """Every DOI in the old output should appear in the new output."""
        _, ref_tex = _get_old_reference()
        old_dois = _extract_dois(ref_tex)
        assert len(old_dois) >= 7, f"Expected >=7 DOIs in reference, got {len(old_dois)}"

        new_html = self._get_new_html(client, db_session)
        new_dois = _extract_dois(new_html)
        missing = old_dois - new_dois
        assert not missing, f"DOIs in old pipeline but not new: {missing}"

    def test_publication_counts_match(self, client, db_session):
        """The new pipeline should have the same number of publications."""
        _setup_new_pipeline(client, db_session)
        papers = client.get("/api/works?type=papers").json()
        chapters = client.get("/api/works?type=chapters").json()
        letters = client.get("/api/works?type=letters").json()
        meetings = client.get("/api/works?type=scimeetings").json()

        # Must match old pipeline's refvars.tex counts
        assert len(papers) == 10     # \npeer{10}
        assert len(chapters) == 2    # \nchapters{2}
        assert len(letters) == 2     # \nletters{2}
        assert len(meetings) == 3    # \npres{3}

    def test_author_names_present(self, client, db_session):
        """Key co-authors should appear in both outputs."""
        new_html = self._get_new_html(client, db_session)
        for name in ["Podolsky", "Rosen", "Infeld", "Bose", "de Haas", "Hoffmann"]:
            assert name in new_html, f"Co-author {name!r} missing from new pipeline"


# ── CV section content comparison ────────────────────────────────────────

class TestSectionContentParity:
    """Verify CV section data matches between old and new pipelines."""

    def _get_both(self, client, db_session):
        tmpl = _setup_new_pipeline(client, db_session)
        new_html = client.get(f"/api/templates/{tmpl['id']}/preview").text
        ref_html, ref_tex = _get_old_reference()
        return new_html, ref_tex

    def test_profile_name(self, client, db_session):
        new_html, ref_tex = self._get_both(client, db_session)
        assert "Albert Einstein" in ref_tex
        assert "Albert Einstein" in new_html

    def test_education_content(self, client, db_session):
        new_html, ref_tex = self._get_both(client, db_session)
        for term in ["PhD", "Diploma", "University of Zurich", "ETH Zurich", "1905", "1900"]:
            assert term in _strip_latex(ref_tex), f"{term!r} missing from old output"
            assert term in new_html, f"{term!r} missing from new output"

    def test_experience_content(self, client, db_session):
        new_html, ref_tex = self._get_both(client, db_session)
        for term in [
            "Institute for Advanced Study",
            "Swiss Patent Office",
            "Humboldt University",
            "1933", "1955", "1902",
        ]:
            assert term in _strip_latex(ref_tex), f"{term!r} missing from old output"
            assert term in new_html, f"{term!r} missing from new output"

    def test_awards_content(self, client, db_session):
        new_html, ref_tex = self._get_both(client, db_session)
        for term in ["Nobel Prize", "Copley Medal", "Max Planck Medal", "1921", "1925"]:
            assert term in _strip_latex(ref_tex), f"{term!r} missing from old output"
            assert term in new_html, f"{term!r} missing from new output"

    def test_memberships_content(self, client, db_session):
        new_html, ref_tex = self._get_both(client, db_session)
        for term in ["Prussian Academy", "Royal Society", "1914"]:
            assert term in _strip_latex(ref_tex), f"{term!r} missing from old output"
            assert term in new_html, f"{term!r} missing from new output"

    def test_patent_content(self, client, db_session):
        new_html, _ = self._get_both(client, db_session)
        # Old pipeline shows 0 patents (Pandoc didn't render the nested authors),
        # but new pipeline should have it
        assert "Refrigerator" in new_html or "Einstein-Szilard" in new_html
        assert "US1781541" in new_html

    def test_year_coverage(self, client, db_session):
        """Key years from Einstein's career should appear in both outputs."""
        new_html, ref_tex = self._get_both(client, db_session)
        key_years = {"1905", "1916", "1921", "1924", "1933", "1935", "1938"}
        old_years = _extract_years(_strip_latex(ref_tex))
        new_years = _extract_years(new_html)
        for y in key_years:
            assert y in old_years, f"Year {y} missing from old output"
            assert y in new_years, f"Year {y} missing from new output"

    def test_contact_info(self, client, db_session):
        new_html, ref_tex = self._get_both(client, db_session)
        assert "einstein@ias.edu" in ref_tex
        assert "einstein@ias.edu" in new_html

    def test_dissertation_content(self, client, db_session):
        new_html, ref_tex = self._get_both(client, db_session)
        assert "Molecular Dimensions" in _strip_latex(ref_tex)
        assert "Molecular Dimensions" in new_html


# ── Structural comparison ────────────────────────────────────────────────

class TestStructuralParity:
    """Verify both pipelines produce the same major sections."""

    # Section headings that should appear in both outputs (may differ in exact wording)
    OLD_SECTION_HEADINGS = [
        "Education",
        "Professional Experience",
        "Honors and Awards",
        "Memberships",
        "Peer-Reviewed Publications",
        "Dissertation",
    ]

    def test_old_sections_present_in_reference(self):
        ref_html, _ = _get_old_reference()
        plain = _strip_html(ref_html)
        for heading in self.OLD_SECTION_HEADINGS:
            assert heading in plain, f"Section {heading!r} missing from old reference"

    def test_new_pipeline_has_all_major_sections(self, client, db_session):
        tmpl = _setup_new_pipeline(client, db_session)
        new_html = client.get(f"/api/templates/{tmpl['id']}/preview").text
        # The new pipeline may use slightly different heading text, so check
        # for key terms rather than exact strings
        for term in ["Education", "Experience", "Award", "Membership",
                      "Publication", "Dissertation"]:
            assert term in new_html, (
                f"Section term {term!r} missing from new pipeline output"
            )
